from typing import List
from report_components.base_component import ReportComponent
import html
from datetime import datetime


class HTMLReportGenerator:
    """Generates a standalone HTML report with PDF download capability."""

    def __init__(self, report_title: str = "Data Quality Analysis Report"):
        self.report_title = report_title

    def generate(self, components: List[ReportComponent], output_path: str = "report.html") -> str:
        """Generate HTML report and save to file."""
        html_content = self._build_html(components)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

        return output_path

    def _build_html(self, components: List[ReportComponent]) -> str:
        sections_html = ""
        toc_html = ""

        for i, component in enumerate(components):
            component_name = component.__class__.__name__
            section_id = f"section-{i}"

            # Build table of contents
            toc_html += f'<li><a href="#{section_id}">{self._format_name(component_name)}</a></li>\n'

            # Build section content
            sections_html += self._build_section(component, section_id, i + 1)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(self.report_title)}</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{html.escape(self.report_title)}</h1>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <button onclick="window.print()" class="download-btn">
                📥 Download as PDF
            </button>
        </header>

        <nav class="toc no-print">
            <h2>Table of Contents</h2>
            <ul>
                {toc_html}
            </ul>
        </nav>

        <main>
            {sections_html}
        </main>

        <footer>
            <p>Generated by AEDA - Automated Exploratory Data Analysis</p>
        </footer>
    </div>

    <script>
        {self._get_scripts()}
    </script>
</body>
</html>"""

    def _build_section(self, component: ReportComponent, section_id: str, number: int) -> str:
        name = self._format_name(component.__class__.__name__)

        try:
            raw_justification = component.justify() or "N/A"
            justification = self._format_justification(raw_justification)
        except Exception:
            justification = "Component analysis incomplete"

        try:
            summary = component.summarize() or {}
        except Exception:
            summary = {"Status": "Analysis failed or skipped"}

        summary_rows = ""
        for key, value in summary.items():
            formatted_value = self._format_value(value)
            summary_rows += f"""
            <tr>
                <td class="key">{html.escape(str(key))}</td>
                <td class="value">{formatted_value}</td>
            </tr>"""

        llm_explanations_html = ""
        component_summary_html = ""
        is_dataset_summary = component.__class__.__name__ == "LLMDatasetSummaryComponent"

        if hasattr(component, 'get_full_summary'):
            full_summary = component.get_full_summary()
            if full_summary and full_summary.strip():
                llm_section, summary_section = self._parse_full_summary(full_summary, is_dataset_summary)

                if llm_section:
                    llm_explanations_html = f"""
                <div class="llm-explanations">
                    <h4>🔍 Semantic Explanations</h4>
                    <div class="llm-content">{llm_section}</div>
                </div>"""

                if summary_section:
                    if is_dataset_summary:
                        component_summary_html = f"""
                <div class="component-summary-box dataset-summary-box">
                    <h4>📊 Analysis Overview</h4>
                    <div class="summary-content-html">{summary_section}</div>
                </div>"""
                    else:
                        component_summary_html = f"""
                <div class="component-summary-box">
                    <h4>📋 Component Summary</h4>
                    <div class="summary-content">{summary_section}</div>
                </div>"""

        return f"""
        <section id="{section_id}" class="component-section">
            <h2><span class="section-number">{number}</span> {html.escape(name)}</h2>

            <div class="justification">
                <h3>Component Description</h3>
                <div class="justification-content">{justification}</div>
            </div>

            <div class="summary">
                <h3>Summary</h3>
                <table>
                    <tbody>
                        {summary_rows}
                    </tbody>
                </table>
            </div>

            {llm_explanations_html}
            {component_summary_html}
        </section>"""

    def _parse_full_summary(self, full_summary: str, is_dataset_summary: bool = False) -> tuple:
        """Parse full summary into semantic explanations and component summary sections."""
        llm_section = ""
        summary_section = ""

        lines = full_summary.split('\n')
        current_section = None
        current_content = []
        ai_assessment_content = []

        for line in lines:
            if '🤖 LLM EXAMPLE EXPLANATIONS' in line or 'LLM EXPLANATIONS' in line:
                current_section = 'llm'
                current_content = []
            elif '📋 COMPONENT SUMMARY' in line or '📊 COMPONENT METRICS OVERVIEW' in line:
                if current_section == 'llm':
                    llm_section = '\n'.join(current_content)
                current_section = 'summary'
                current_content = []
            elif '🤖 AI QUALITY ASSESSMENT' in line:
                if current_section == 'summary':
                    summary_section = '\n'.join(current_content)
                current_section = 'ai_assessment'
                current_content = []
            elif '=' * 10 in line:
                continue
            elif current_section:
                current_content.append(line)

        if current_section == 'llm':
            llm_section = '\n'.join(current_content)
        elif current_section == 'summary':
            summary_section = '\n'.join(current_content)
        elif current_section == 'ai_assessment':
            ai_assessment_content = current_content

        if not llm_section and not summary_section and full_summary.strip():
            summary_section = full_summary

        llm_section = html.escape(llm_section.strip())

        if is_dataset_summary and summary_section:
            summary_section = self._format_metrics_as_html(summary_section.strip())
            if ai_assessment_content:
                summary_section += self._format_ai_assessment_as_html(ai_assessment_content)
        else:
            summary_section = html.escape(summary_section.strip())

        return llm_section, summary_section

    def _format_metrics_as_html(self, metrics_text: str) -> str:
        """Format component metrics as a nice HTML grid."""
        lines = metrics_text.split('\n')
        cards = []
        current_card = None

        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith('📌'):
                if current_card:
                    cards.append(current_card)
                current_card = {'title': line.replace('📌', '').strip(), 'metrics': []}
            elif line.startswith('•') and current_card:
                current_card['metrics'].append(line.replace('•', '').strip())

        if current_card:
            cards.append(current_card)

        if not cards:
            return html.escape(metrics_text)

        html_parts = ['<div class="metrics-grid">']
        for card in cards:
            metrics_html = ''.join([f'<div class="metric-item">{html.escape(m)}</div>' for m in card['metrics']])
            html_parts.append(f'''
                <div class="metric-card">
                    <div class="metric-title">{html.escape(card['title'])}</div>
                    {metrics_html}
                </div>
            ''')
        html_parts.append('</div>')

        return ''.join(html_parts)

    def _format_ai_assessment_as_html(self, ai_lines: list) -> str:
        """Format AI assessment as a beautiful HTML table with strengths and weaknesses."""
        text = '\n'.join(ai_lines)

        strengths = []
        issues = []
        priority = ""

        current_section = None
        for line in ai_lines:
            line = line.strip()
            if not line:
                continue
            if '✅' in line and 'STRENGTH' in line.upper():
                current_section = 'strengths'
                continue
            elif '❌' in line and 'ISSUE' in line.upper():
                current_section = 'issues'
                continue
            elif '🎯' in line and 'PRIORITY' in line.upper():
                current_section = 'priority'
                continue

            if current_section == 'strengths' and line.startswith(('•', '-', '*')):
                strengths.append(line.lstrip('•-* '))
            elif current_section == 'issues' and line.startswith(('•', '-', '*')):
                issues.append(line.lstrip('•-* '))
            elif current_section == 'priority':
                priority = line.lstrip('•-* ')

        if not strengths and not issues:
            return f'<div class="ai-assessment-text">{html.escape(text)}</div>'

        strengths_html = ''.join([f'<tr><td class="strength-icon">✅</td><td>{html.escape(s)}</td></tr>' for s in strengths])
        issues_html = ''.join([f'<tr><td class="issue-icon">❌</td><td>{html.escape(i)}</td></tr>' for i in issues])

        priority_html = ""
        if priority:
            priority_html = f'''
                <div class="priority-action">
                    <span class="priority-icon">🎯</span>
                    <span class="priority-text"><strong>Priority Action:</strong> {html.escape(priority)}</span>
                </div>
            '''

        return f'''
            <div class="ai-assessment-container">
                <h5>AI Quality Assessment</h5>
                <div class="assessment-tables">
                    <div class="assessment-column strengths-column">
                        <h6>✅ Strengths</h6>
                        <table class="assessment-table">
                            {strengths_html}
                        </table>
                    </div>
                    <div class="assessment-column issues-column">
                        <h6>❌ Issues</h6>
                        <table class="assessment-table">
                            {issues_html}
                        </table>
                    </div>
                </div>
                {priority_html}
            </div>
        '''

    def _format_name(self, name: str) -> str:
        """Convert CamelCase to readable format."""
        import re
        if name == "LLMDatasetSummaryComponent":
            return "Dataset Summary"
        name = name.replace("Component", "").replace("Report", "")
        return re.sub(r'(?<!^)(?=[A-Z])', ' ', name)

    def _format_justification(self, text: str) -> str:
        """Convert markdown-style formatting in justifications to HTML."""
        import re

        # Escape HTML first
        text = html.escape(text)

        # Convert **bold** to <strong>
        text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)

        # Convert *italic* to <em>
        text = re.sub(r'\*(.+?)\*', r'<em>\1</em>', text)

        # Convert `code` to <code>
        text = re.sub(r'`(.+?)`', r'<code>\1</code>', text)

        # Split into paragraphs by double newlines
        paragraphs = re.split(r'\n\s*\n', text)

        formatted_parts = []

        for para in paragraphs:
            para = para.strip()
            if not para:
                continue

            # Check if this paragraph contains numbered list items
            lines = para.split('\n')
            list_items = []
            non_list_lines = []

            for line in lines:
                line = line.strip()
                if not line:
                    continue
                # Check for numbered list (1. 2. 3.)
                match = re.match(r'^(\d+)\.\s+(.+)$', line)
                if match:
                    list_items.append(match.group(2))
                else:
                    # Check for bullet list (- or *)
                    match = re.match(r'^[-*]\s+(.+)$', line)
                    if match:
                        list_items.append(match.group(1))
                    else:
                        non_list_lines.append(line)

            # Output non-list content as paragraph
            if non_list_lines:
                formatted_parts.append(f'<p>{" ".join(non_list_lines)}</p>')

            # Output list items
            if list_items:
                items_html = ''.join([f'<li>{item}</li>' for item in list_items])
                formatted_parts.append(f'<ol>{items_html}</ol>')

        return ''.join(formatted_parts) if formatted_parts else text

    def _format_value(self, value) -> str:
        """Format values for HTML display."""
        if isinstance(value, float):
            if abs(value) < 1:
                return f"{value:.4f}"
            return f"{value:.2f}"
        elif isinstance(value, list):
            if not value:
                return "<em>None</em>"
            # Check if it's a list of dictionaries (example outliers, etc.)
            if isinstance(value[0], dict):
                return self._format_examples_list(value)
            # Check if it's a list of tuples (worst_columns, etc.)
            elif isinstance(value[0], tuple) and len(value[0]) == 2:
                return self._format_tuple_list(value)
            elif len(value) > 5:
                return html.escape(str(value[:5])) + f"... ({len(value)} items)"
            return html.escape(str(value))
        elif isinstance(value, dict):
            items = [f"<strong>{html.escape(str(k))}:</strong> {html.escape(str(v))}"
                     for k, v in list(value.items())[:10]]
            return "<br>".join(items)
        return html.escape(str(value))

    def _format_examples_list(self, examples: list) -> str:
        """Format a list of example dictionaries as beautiful HTML cards."""
        if not examples:
            return "<em>No examples</em>"

        # Limit to first 5 examples
        examples = examples[:5]

        html_parts = [f'<div class="examples-container"><span class="examples-count">{len(examples)} example(s)</span>']

        for i, example in enumerate(examples, 1):
            # Determine the type of example and format accordingly
            card_content = self._format_single_example(example, i)
            html_parts.append(card_content)

        html_parts.append('</div>')
        return ''.join(html_parts)

    def _format_single_example(self, example: dict, index: int) -> str:
        """Format a single example dictionary as an HTML card."""
        # Identify key fields for different types of examples
        row_idx = example.get('row_index', example.get('index', None))

        # Build header
        if row_idx is not None:
            header = f"Row {row_idx}"
        elif 'column' in example:
            header = f"Column: {example['column']}"
        else:
            header = f"Example {index}"

        # Build metrics based on what's in the example
        metrics = []

        # Common fields to display nicely
        field_labels = {
            'outlier_score': ('Score', lambda v: f"{v:.3f}"),
            'score': ('Score', lambda v: f"{v:.3f}"),
            'frequency': ('Frequency', lambda v: f"{v:.4f}"),
            'error': ('Error', lambda v: f"{v:.4f}"),
            'reconstruction_error': ('Recon. Error', lambda v: f"{v:.4f}"),
            'similarity': ('Similarity', lambda v: f"{v:.1%}"),
            'confidence': ('Confidence', lambda v: f"{v:.1%}"),
            'noise_score': ('Noise Score', lambda v: f"{v:.3f}"),
            'value': ('Value', lambda v: html.escape(str(v))),
            'column': ('Column', lambda v: html.escape(str(v))),
            'narrative': ('Details', lambda v: html.escape(str(v)[:100])),
            'explanation_narrative': ('Details', lambda v: html.escape(str(v)[:100])),
        }

        for field, (label, formatter) in field_labels.items():
            if field in example and example[field] is not None:
                try:
                    formatted_val = formatter(example[field])
                    metrics.append(f'<div class="example-metric"><span class="metric-label">{label}:</span> <span class="metric-value">{formatted_val}</span></div>')
                except:
                    pass

        # Handle top_contributing_features specially
        if 'top_contributing_features' in example:
            features = example['top_contributing_features']
            if isinstance(features, dict):
                top_3 = list(features.items())[:3]
                features_str = ', '.join([f"{k}: {v:.2f}" for k, v in top_3])
                metrics.append(f'<div class="example-metric"><span class="metric-label">Top Features:</span> <span class="metric-value">{html.escape(features_str)}</span></div>')

        # Handle matching/differing columns for near-duplicates
        if 'matching_columns' in example:
            cols = example['matching_columns'][:3]
            metrics.append(f'<div class="example-metric"><span class="metric-label">Matching:</span> <span class="metric-value">{html.escape(", ".join(cols))}</span></div>')

        if 'differing_columns' in example:
            cols = example['differing_columns'][:3]
            metrics.append(f'<div class="example-metric"><span class="metric-label">Differing:</span> <span class="metric-value">{html.escape(", ".join(cols))}</span></div>')

        metrics_html = ''.join(metrics) if metrics else '<div class="example-metric"><em>No details</em></div>'

        return f'''
            <div class="example-card">
                <div class="example-header">{html.escape(header)}</div>
                <div class="example-body">{metrics_html}</div>
            </div>
        '''

    def _format_tuple_list(self, tuples: list) -> str:
        """Format a list of tuples (like worst_columns) as a nice list."""
        if not tuples:
            return "<em>None</em>"

        items = []
        for name, value in tuples[:5]:
            if isinstance(value, float):
                items.append(f'<div class="tuple-item"><strong>{html.escape(str(name))}:</strong> {value:.2%}</div>')
            else:
                items.append(f'<div class="tuple-item"><strong>{html.escape(str(name))}:</strong> {html.escape(str(value))}</div>')

        if len(tuples) > 5:
            items.append(f'<div class="tuple-item"><em>... and {len(tuples) - 5} more</em></div>')

        return '<div class="tuple-list">' + ''.join(items) + '</div>'

    def _get_styles(self) -> str:
        return """
        :root {
            --primary: #2563eb;
            --primary-dark: #1d4ed8;
            --success: #22c55e;
            --warning: #f59e0b;
            --danger: #ef4444;
            --bg: #e8f0fe;
            --card-bg: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #d1d9e6;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background-color: #e8f0fe;
            color: var(--text);
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        header {
            text-align: center;
            margin-bottom: 3rem;
            padding: 2rem;
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
            color: white;
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }

        header h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

        .timestamp {
            opacity: 0.9;
            font-size: 0.9rem;
        }

        .download-btn {
            margin-top: 1rem;
            padding: 0.75rem 2rem;
            font-size: 1rem;
            font-weight: 600;
            color: var(--primary);
            background: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        .download-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        }

        .toc {
            background-color: #f8faff;
            padding: 1.5rem 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            border: 1px solid #d1d9e6;
        }

        .toc h2 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            color: var(--primary);
        }

        .toc ul {
            list-style: none;
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 0.5rem;
        }

        .toc a {
            color: var(--text);
            text-decoration: none;
            padding: 0.5rem;
            display: block;
            border-radius: 6px;
            transition: background 0.2s;
        }

        .toc a:hover {
            background: var(--bg);
            color: var(--primary);
        }

        .component-section {
            background-color: #f8faff;
            border-radius: 12px;
            padding: 2rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            page-break-inside: avoid;
            border: 1px solid #d1d9e6;
        }

        .component-section h2 {
            font-size: 1.5rem;
            color: var(--primary);
            margin-bottom: 1.5rem;
            padding-bottom: 0.75rem;
            border-bottom: 2px solid var(--border);
        }

        .section-number {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 2rem;
            height: 2rem;
            background: var(--primary);
            color: white;
            border-radius: 50%;
            font-size: 0.9rem;
            margin-right: 0.5rem;
        }

        .justification, .summary, .full-summary {
            margin-bottom: 1.5rem;
        }

        .justification h3, .summary h3, .full-summary h4 {
            font-size: 1rem;
            color: var(--text-muted);
            margin-bottom: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .justification-content {
            background-color: #eef4ff;
            padding: 1.25rem;
            border-radius: 8px;
            border-left: 4px solid var(--primary);
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
        }

        .justification-content p {
            margin: 0 0 0.75rem 0;
        }

        .justification-content p:last-child {
            margin-bottom: 0;
        }

        .justification-content ol, .justification-content ul {
            margin: 0.75rem 0;
            padding-left: 1.5rem;
        }

        .justification-content li {
            margin-bottom: 0.5rem;
            line-height: 1.6;
        }

        .justification-content strong {
            color: #1e40af;
            font-weight: 600;
        }

        .justification-content em {
            color: #4338ca;
            font-style: italic;
        }

        .justification-content code {
            background: #e0e7ff;
            padding: 0.15rem 0.4rem;
            border-radius: 4px;
            font-family: 'Monaco', 'Consolas', monospace;
            font-size: 0.85em;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table tr {
            border-bottom: 1px solid var(--border);
        }

        table tr:last-child {
            border-bottom: none;
        }

        table td {
            padding: 0.75rem;
            text-align: center;
            vertical-align: middle;
        }

        table td.key {
            font-weight: 600;
            width: 30%;
            color: var(--text-muted);
            text-align: center;
        }

        table td.value {
            font-family: 'Monaco', 'Consolas', monospace;
            font-size: 0.9rem;
            text-align: center;
        }

        .full-summary pre {
            background-color: #eef4ff;
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 0.85rem;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .llm-explanations {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: linear-gradient(135deg, #f0f7ff 0%, #e8f4f8 100%);
            border-radius: 10px;
            border-left: 4px solid #3b82f6;
        }

        .llm-explanations h4 {
            font-size: 1rem;
            color: #1e40af;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .llm-content {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
            white-space: pre-wrap;
        }

        .component-summary-box {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: linear-gradient(135deg, #f0fdf4 0%, #ecfdf5 100%);
            border-radius: 10px;
            border-left: 4px solid #22c55e;
        }

        .component-summary-box h4 {
            font-size: 1rem;
            color: #166534;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .summary-content {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
            white-space: pre-wrap;
        }

        .summary-content-html {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
        }

        .dataset-summary-box {
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
            border-left: 4px solid #6366f1;
        }

        .dataset-summary-box h4 {
            color: #4338ca;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 1.5rem;
        }

        .metric-card {
            background: white;
            border-radius: 8px;
            padding: 1rem;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border: 1px solid #e2e8f0;
        }

        .metric-title {
            font-weight: 600;
            color: #4338ca;
            margin-bottom: 0.5rem;
            font-size: 0.9rem;
        }

        .metric-item {
            font-size: 0.85rem;
            color: #475569;
            padding: 0.25rem 0;
        }

        .ai-assessment-container {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: white;
            border-radius: 10px;
            border: 1px solid #e2e8f0;
        }

        .ai-assessment-container h5 {
            font-size: 1rem;
            color: #1e293b;
            margin-bottom: 1rem;
            font-weight: 600;
        }

        .assessment-tables {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1.5rem;
        }

        .assessment-column {
            padding: 1rem;
            border-radius: 8px;
        }

        .strengths-column {
            background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);
        }

        .issues-column {
            background: linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%);
        }

        .assessment-column h6 {
            font-size: 0.9rem;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .strengths-column h6 {
            color: #166534;
        }

        .issues-column h6 {
            color: #991b1b;
        }

        .assessment-table {
            width: 100%;
        }

        .assessment-table tr {
            border: none;
        }

        .assessment-table td {
            padding: 0.4rem 0.5rem;
            font-size: 0.85rem;
            text-align: left;
            vertical-align: top;
        }

        .strength-icon, .issue-icon {
            width: 24px;
            font-size: 1rem;
        }

        .priority-action {
            margin-top: 1rem;
            padding: 1rem;
            background: linear-gradient(135deg, #fefce8 0%, #fef9c3 100%);
            border-radius: 8px;
            display: flex;
            align-items: flex-start;
            gap: 0.5rem;
        }

        .priority-icon {
            font-size: 1.2rem;
        }

        .priority-text {
            font-size: 0.9rem;
            color: #854d0e;
        }

        .ai-assessment-text {
            white-space: pre-wrap;
            font-size: 0.9rem;
            color: #334155;
        }

        /* Example cards styling */
        .examples-container {
            display: flex;
            flex-wrap: wrap;
            gap: 0.75rem;
            margin-top: 0.5rem;
        }

        .examples-count {
            width: 100%;
            font-size: 0.8rem;
            color: #64748b;
            margin-bottom: 0.25rem;
        }

        .example-card {
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
            border: 1px solid #e2e8f0;
            border-radius: 8px;
            padding: 0.75rem;
            min-width: 180px;
            max-width: 280px;
            flex: 1;
        }

        .example-header {
            font-weight: 600;
            color: #4338ca;
            font-size: 0.85rem;
            margin-bottom: 0.5rem;
            padding-bottom: 0.4rem;
            border-bottom: 1px solid #e2e8f0;
        }

        .example-body {
            font-size: 0.8rem;
        }

        .example-metric {
            padding: 0.2rem 0;
            color: #475569;
        }

        .metric-label {
            color: #64748b;
            font-size: 0.75rem;
        }

        .metric-value {
            color: #1e293b;
            font-weight: 500;
        }

        /* Tuple list styling (for worst_columns etc.) */
        .tuple-list {
            display: flex;
            flex-direction: column;
            gap: 0.25rem;
        }

        .tuple-item {
            font-size: 0.85rem;
            padding: 0.25rem 0.5rem;
            background: #f8fafc;
            border-radius: 4px;
            border-left: 3px solid #6366f1;
        }

        .tuple-item strong {
            color: #4338ca;
        }

        footer {
            text-align: center;
            padding: 2rem;
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        /* Print styles */
        @media print {
            .no-print {
                display: none !important;
            }

            body {
                background: white;}

            .container {
                max-width: none;padding: 0;
            }

            header {
                background: var(--primary) !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

            .component-section {
                box-shadow: none;
                border: 1px solid var(--border);
                break-inside: avoid;
            }

            .download-btn {
                display: none;
            }
        }
        """

    def _get_scripts(self) -> str:
        return """
        // Smooth scrolling for TOC links
        document.querySelectorAll('.toc a').forEach(anchor => {
            anchor.addEventListener('click', function(e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            });
        });
        """
