from typing import List
from report_components.base_component import ReportComponent
import html
from datetime import datetime


class HTMLReportGenerator:
    """Generates a standalone HTML report with PDF download capability."""

    def __init__(self, report_title: str = "Data Quality Analysis Report"):
        self.report_title = report_title

    def generate(self, components: List[ReportComponent], output_path: str = "report.html") -> str:
        """Generate HTML report and save to file."""
        html_content = self._build_html(components)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

        return output_path

    def _build_html(self, components: List[ReportComponent]) -> str:
        sections_html = ""
        toc_html = ""

        for i, component in enumerate(components):
            component_name = component.__class__.__name__
            section_id = f"section-{i}"

            # Build table of contents
            toc_html += f'<li><a href="#{section_id}">{self._format_name(component_name)}</a></li>\n'

            # Build section content
            sections_html += self._build_section(component, section_id, i + 1)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(self.report_title)}</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{html.escape(self.report_title)}</h1>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <button onclick="window.print()" class="download-btn">
                📥 Download as PDF
            </button>
        </header>

        <nav class="toc no-print">
            <h2>Table of Contents</h2>
            <ul>
                {toc_html}
            </ul>
        </nav>

        <main>
            {sections_html}
        </main>

        <footer>
            <p>Generated by AEDA - Automated Exploratory Data Analysis</p>
        </footer>
    </div>

    <script>
        {self._get_scripts()}
    </script>
</body>
</html>"""

    def _build_section(self, component: ReportComponent, section_id: str, number: int) -> str:
        name = self._format_name(component.__class__.__name__)

        try:
            justification = html.escape(component.justify() or "N/A")
        except Exception:
            justification = "Component analysis incomplete"

        try:
            summary = component.summarize() or {}
        except Exception:
            summary = {"Status": "Analysis failed or skipped"}

        summary_rows = ""
        for key, value in summary.items():
            formatted_value = self._format_value(value)
            summary_rows += f"""
            <tr>
                <td class="key">{html.escape(str(key))}</td>
                <td class="value">{formatted_value}</td>
            </tr>"""

        llm_explanations_html = ""
        component_summary_html = ""

        if hasattr(component, 'get_full_summary'):
            full_summary = component.get_full_summary()
            if full_summary and full_summary.strip():
                llm_section, summary_section = self._parse_full_summary(full_summary)

                if llm_section:
                    llm_explanations_html = f"""
                <div class="llm-explanations">
                    <h4>🤖 LLM Example Explanations</h4>
                    <div class="llm-content">{llm_section}</div>
                </div>"""

                if summary_section:
                    component_summary_html = f"""
                <div class="component-summary-box">
                    <h4>📋 Component Summary</h4>
                    <div class="summary-content">{summary_section}</div>
                </div>"""

        return f"""
        <section id="{section_id}" class="component-section">
            <h2><span class="section-number">{number}</span> {html.escape(name)}</h2>

            <div class="justification">
                <h3>Component Description</h3>
                <p>{justification}</p>
            </div>

            <div class="summary">
                <h3>Summary</h3>
                <table>
                    <tbody>
                        {summary_rows}
                    </tbody>
                </table>
            </div>

            {llm_explanations_html}
            {component_summary_html}
        </section>"""

    def _parse_full_summary(self, full_summary: str) -> tuple:
        """Parse full summary into LLM explanations and component summary sections."""
        llm_section = ""
        summary_section = ""

        lines = full_summary.split('\n')
        current_section = None
        current_content = []

        for line in lines:
            if '🤖 LLM EXAMPLE EXPLANATIONS' in line or 'LLM EXPLANATIONS' in line:
                current_section = 'llm'
                current_content = []
            elif '📋 COMPONENT SUMMARY' in line:
                if current_section == 'llm':
                    llm_section = '\n'.join(current_content)
                current_section = 'summary'
                current_content = []
            elif '=' * 10 in line:
                continue
            elif current_section:
                current_content.append(line)

        if current_section == 'llm':
            llm_section = '\n'.join(current_content)
        elif current_section == 'summary':
            summary_section = '\n'.join(current_content)

        if not llm_section and not summary_section and full_summary.strip():
            summary_section = full_summary

        llm_section = html.escape(llm_section.strip())
        summary_section = html.escape(summary_section.strip())

        return llm_section, summary_section

    def _format_name(self, name: str) -> str:
        """Convert CamelCase to readable format."""
        import re
        name = name.replace("Component", "").replace("Report", "")
        return re.sub(r'(?<!^)(?=[A-Z])', ' ', name)

    def _format_value(self, value) -> str:
        """Format values for HTML display."""
        if isinstance(value, float):
            return f"{value:.4f}"
        elif isinstance(value, list):
            if len(value) > 10:
                return html.escape(str(value[:10])) + f"... ({len(value)} items)"
            return html.escape(str(value))
        elif isinstance(value, dict):
            items = [f"<strong>{html.escape(str(k))}:</strong> {html.escape(str(v))}"
                     for k, v in list(value.items())[:10]]
            return "<br>".join(items)
        return html.escape(str(value))

    def _get_styles(self) -> str:
        return """
        :root {
            --primary: #2563eb;
            --primary-dark: #1d4ed8;
            --success: #22c55e;
            --warning: #f59e0b;
            --danger: #ef4444;
            --bg: #e8f0fe;
            --card-bg: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #d1d9e6;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background-color: #e8f0fe;
            color: var(--text);
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        header {
            text-align: center;
            margin-bottom: 3rem;
            padding: 2rem;
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
            color: white;
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }

        header h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

        .timestamp {
            opacity: 0.9;
            font-size: 0.9rem;
        }

        .download-btn {
            margin-top: 1rem;
            padding: 0.75rem 2rem;
            font-size: 1rem;
            font-weight: 600;
            color: var(--primary);
            background: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        .download-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        }

        .toc {
            background-color: #f8faff;
            padding: 1.5rem 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            border: 1px solid #d1d9e6;
        }

        .toc h2 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            color: var(--primary);
        }

        .toc ul {
            list-style: none;
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 0.5rem;
        }

        .toc a {
            color: var(--text);
            text-decoration: none;
            padding: 0.5rem;
            display: block;
            border-radius: 6px;
            transition: background 0.2s;
        }

        .toc a:hover {
            background: var(--bg);
            color: var(--primary);
        }

        .component-section {
            background-color: #f8faff;
            border-radius: 12px;
            padding: 2rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            page-break-inside: avoid;
            border: 1px solid #d1d9e6;
        }

        .component-section h2 {
            font-size: 1.5rem;
            color: var(--primary);
            margin-bottom: 1.5rem;
            padding-bottom: 0.75rem;
            border-bottom: 2px solid var(--border);
        }

        .section-number {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 2rem;
            height: 2rem;
            background: var(--primary);
            color: white;
            border-radius: 50%;
            font-size: 0.9rem;
            margin-right: 0.5rem;
        }

        .justification, .summary, .full-summary {
            margin-bottom: 1.5rem;
        }

        .justification h3, .summary h3, .full-summary h4 {
            font-size: 1rem;
            color: var(--text-muted);
            margin-bottom: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .justification p {
            background-color: #eef4ff;
            padding: 1rem;
            border-radius: 8px;
            border-left: 4px solid var(--primary);
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table tr {
            border-bottom: 1px solid var(--border);
        }

        table tr:last-child {
            border-bottom: none;
        }

        table td {
            padding: 0.75rem;
            text-align: center;
            vertical-align: middle;
        }

        table td.key {
            font-weight: 600;
            width: 30%;
            color: var(--text-muted);
            text-align: center;
        }

        table td.value {
            font-family: 'Monaco', 'Consolas', monospace;
            font-size: 0.9rem;
            text-align: center;
        }

        .full-summary pre {
            background-color: #eef4ff;
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 0.85rem;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .llm-explanations {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: linear-gradient(135deg, #f0f7ff 0%, #e8f4f8 100%);
            border-radius: 10px;
            border-left: 4px solid #3b82f6;
        }

        .llm-explanations h4 {
            font-size: 1rem;
            color: #1e40af;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .llm-content {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
            white-space: pre-wrap;
        }

        .component-summary-box {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: linear-gradient(135deg, #f0fdf4 0%, #ecfdf5 100%);
            border-radius: 10px;
            border-left: 4px solid #22c55e;
        }

        .component-summary-box h4 {
            font-size: 1rem;
            color: #166534;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .summary-content {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
            white-space: pre-wrap;
        }

        footer {
            text-align: center;
            padding: 2rem;
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        /* Print styles */
        @media print {
            .no-print {
                display: none !important;
            }

            body {
                background: white;}

            .container {
                max-width: none;padding: 0;
            }

            header {
                background: var(--primary) !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

            .component-section {
                box-shadow: none;
                border: 1px solid var(--border);
                break-inside: avoid;
            }

            .download-btn {
                display: none;
            }
        }
        """

    def _get_scripts(self) -> str:
        return """
        // Smooth scrolling for TOC links
        document.querySelectorAll('.toc a').forEach(anchor => {
            anchor.addEventListener('click', function(e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            });
        });
        """
