from typing import List
from report_components.base_component import ReportComponent
import html
from datetime import datetime


class HTMLReportGenerator:
    """Generates a standalone HTML report with PDF download capability."""

    def __init__(self, report_title: str = "Data Quality Analysis Report"):
        self.report_title = report_title

    def generate(self, components: List[ReportComponent], output_path: str = "report.html") -> str:
        """Generate HTML report and save to file."""
        html_content = self._build_html(components)

        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(html_content)

        return output_path

    def _build_html(self, components: List[ReportComponent]) -> str:
        sections_html = ""
        toc_html = ""

        for i, component in enumerate(components):
            component_name = component.__class__.__name__
            section_id = f"section-{i}"

            # Build table of contents
            toc_html += f'<li><a href="#{section_id}">{self._format_name(component_name)}</a></li>\n'

            # Build section content
            sections_html += self._build_section(component, section_id, i + 1)

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{html.escape(self.report_title)}</title>
    <style>
        {self._get_styles()}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>{html.escape(self.report_title)}</h1>
            <p class="timestamp">Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
            <button onclick="window.print()" class="download-btn">
                📥 Download as PDF
            </button>
        </header>

        <nav class="toc no-print">
            <h2>Table of Contents</h2>
            <ul>
                {toc_html}
            </ul>
        </nav>

        <main>
            {sections_html}
        </main>

        <footer>
            <p>Generated by AEDA - Automated Exploratory Data Analysis</p>
        </footer>
    </div>

    <script>
        {self._get_scripts()}
    </script>
</body>
</html>"""

    def _build_section(self, component: ReportComponent, section_id: str, number: int) -> str:
        name = self._format_name(component.__class__.__name__)

        try:
            justification = html.escape(component.justify() or "N/A")
        except Exception:
            justification = "Component analysis incomplete"

        try:
            summary = component.summarize() or {}
        except Exception:
            summary = {"Status": "Analysis failed or skipped"}

        summary_rows = ""
        for key, value in summary.items():
            formatted_value = self._format_value(value)
            summary_rows += f"""
            <tr>
                <td class="key">{html.escape(str(key))}</td>
                <td class="value">{formatted_value}</td>
            </tr>"""

        llm_explanations_html = ""
        component_summary_html = ""
        is_dataset_summary = component.__class__.__name__ == "LLMDatasetSummaryComponent"

        if hasattr(component, 'get_full_summary'):
            full_summary = component.get_full_summary()
            if full_summary and full_summary.strip():
                llm_section, summary_section = self._parse_full_summary(full_summary, is_dataset_summary)

                if llm_section:
                    llm_explanations_html = f"""
                <div class="llm-explanations">
                    <h4>🔍 Semantic Explanations</h4>
                    <div class="llm-content">{llm_section}</div>
                </div>"""

                if summary_section:
                    if is_dataset_summary:
                        component_summary_html = f"""
                <div class="component-summary-box dataset-summary-box">
                    <h4>📊 Analysis Overview</h4>
                    <div class="summary-content-html">{summary_section}</div>
                </div>"""
                    else:
                        component_summary_html = f"""
                <div class="component-summary-box">
                    <h4>📋 Component Summary</h4>
                    <div class="summary-content">{summary_section}</div>
                </div>"""

        return f"""
        <section id="{section_id}" class="component-section">
            <h2><span class="section-number">{number}</span> {html.escape(name)}</h2>

            <div class="justification">
                <h3>Component Description</h3>
                <p>{justification}</p>
            </div>

            <div class="summary">
                <h3>Summary</h3>
                <table>
                    <tbody>
                        {summary_rows}
                    </tbody>
                </table>
            </div>

            {llm_explanations_html}
            {component_summary_html}
        </section>"""

    def _parse_full_summary(self, full_summary: str, is_dataset_summary: bool = False) -> tuple:
        """Parse full summary into semantic explanations and component summary sections."""
        llm_section = ""
        summary_section = ""

        lines = full_summary.split('\n')
        current_section = None
        current_content = []
        ai_assessment_content = []

        for line in lines:
            if '🤖 LLM EXAMPLE EXPLANATIONS' in line or 'LLM EXPLANATIONS' in line:
                current_section = 'llm'
                current_content = []
            elif '📋 COMPONENT SUMMARY' in line or '📊 COMPONENT METRICS OVERVIEW' in line:
                if current_section == 'llm':
                    llm_section = '\n'.join(current_content)
                current_section = 'summary'
                current_content = []
            elif '🤖 AI QUALITY ASSESSMENT' in line:
                if current_section == 'summary':
                    summary_section = '\n'.join(current_content)
                current_section = 'ai_assessment'
                current_content = []
            elif '=' * 10 in line:
                continue
            elif current_section:
                current_content.append(line)

        if current_section == 'llm':
            llm_section = '\n'.join(current_content)
        elif current_section == 'summary':
            summary_section = '\n'.join(current_content)
        elif current_section == 'ai_assessment':
            ai_assessment_content = current_content

        if not llm_section and not summary_section and full_summary.strip():
            summary_section = full_summary

        llm_section = html.escape(llm_section.strip())

        if is_dataset_summary and summary_section:
            summary_section = self._format_metrics_as_html(summary_section.strip())
            if ai_assessment_content:
                summary_section += self._format_ai_assessment_as_html(ai_assessment_content)
        else:
            summary_section = html.escape(summary_section.strip())

        return llm_section, summary_section

    def _format_metrics_as_html(self, metrics_text: str) -> str:
        """Format component metrics as a nice HTML grid."""
        lines = metrics_text.split('\n')
        cards = []
        current_card = None

        for line in lines:
            line = line.strip()
            if not line:
                continue
            if line.startswith('📌'):
                if current_card:
                    cards.append(current_card)
                current_card = {'title': line.replace('📌', '').strip(), 'metrics': []}
            elif line.startswith('•') and current_card:
                current_card['metrics'].append(line.replace('•', '').strip())

        if current_card:
            cards.append(current_card)

        if not cards:
            return html.escape(metrics_text)

        html_parts = ['<div class="metrics-grid">']
        for card in cards:
            metrics_html = ''.join([f'<div class="metric-item">{html.escape(m)}</div>' for m in card['metrics']])
            html_parts.append(f'''
                <div class="metric-card">
                    <div class="metric-title">{html.escape(card['title'])}</div>
                    {metrics_html}
                </div>
            ''')
        html_parts.append('</div>')

        return ''.join(html_parts)

    def _format_ai_assessment_as_html(self, ai_lines: list) -> str:
        """Format AI assessment as a beautiful HTML table with strengths and weaknesses."""
        text = '\n'.join(ai_lines)

        strengths = []
        issues = []
        priority = ""

        current_section = None
        for line in ai_lines:
            line = line.strip()
            if not line:
                continue
            if '✅' in line and 'STRENGTH' in line.upper():
                current_section = 'strengths'
                continue
            elif '❌' in line and 'ISSUE' in line.upper():
                current_section = 'issues'
                continue
            elif '🎯' in line and 'PRIORITY' in line.upper():
                current_section = 'priority'
                continue

            if current_section == 'strengths' and line.startswith(('•', '-', '*')):
                strengths.append(line.lstrip('•-* '))
            elif current_section == 'issues' and line.startswith(('•', '-', '*')):
                issues.append(line.lstrip('•-* '))
            elif current_section == 'priority':
                priority = line.lstrip('•-* ')

        if not strengths and not issues:
            return f'<div class="ai-assessment-text">{html.escape(text)}</div>'

        strengths_html = ''.join([f'<tr><td class="strength-icon">✅</td><td>{html.escape(s)}</td></tr>' for s in strengths])
        issues_html = ''.join([f'<tr><td class="issue-icon">❌</td><td>{html.escape(i)}</td></tr>' for i in issues])

        priority_html = ""
        if priority:
            priority_html = f'''
                <div class="priority-action">
                    <span class="priority-icon">🎯</span>
                    <span class="priority-text"><strong>Priority Action:</strong> {html.escape(priority)}</span>
                </div>
            '''

        return f'''
            <div class="ai-assessment-container">
                <h5>AI Quality Assessment</h5>
                <div class="assessment-tables">
                    <div class="assessment-column strengths-column">
                        <h6>✅ Strengths</h6>
                        <table class="assessment-table">
                            {strengths_html}
                        </table>
                    </div>
                    <div class="assessment-column issues-column">
                        <h6>❌ Issues</h6>
                        <table class="assessment-table">
                            {issues_html}
                        </table>
                    </div>
                </div>
                {priority_html}
            </div>
        '''

    def _format_name(self, name: str) -> str:
        """Convert CamelCase to readable format."""
        import re
        if name == "LLMDatasetSummaryComponent":
            return "Dataset Summary"
        name = name.replace("Component", "").replace("Report", "")
        return re.sub(r'(?<!^)(?=[A-Z])', ' ', name)

    def _format_value(self, value) -> str:
        """Format values for HTML display."""
        if isinstance(value, float):
            return f"{value:.4f}"
        elif isinstance(value, list):
            if len(value) > 10:
                return html.escape(str(value[:10])) + f"... ({len(value)} items)"
            return html.escape(str(value))
        elif isinstance(value, dict):
            items = [f"<strong>{html.escape(str(k))}:</strong> {html.escape(str(v))}"
                     for k, v in list(value.items())[:10]]
            return "<br>".join(items)
        return html.escape(str(value))

    def _get_styles(self) -> str:
        return """
        :root {
            --primary: #2563eb;
            --primary-dark: #1d4ed8;
            --success: #22c55e;
            --warning: #f59e0b;
            --danger: #ef4444;
            --bg: #e8f0fe;
            --card-bg: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #d1d9e6;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background-color: #e8f0fe;
            color: var(--text);
            line-height: 1.6;
        }

        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem;
        }

        header {
            text-align: center;
            margin-bottom: 3rem;
            padding: 2rem;
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
            color: white;
            border-radius: 16px;
            box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
        }

        header h1 {
            font-size: 2.5rem;
            margin-bottom: 0.5rem;
        }

        .timestamp {
            opacity: 0.9;
            font-size: 0.9rem;
        }

        .download-btn {
            margin-top: 1rem;
            padding: 0.75rem 2rem;
            font-size: 1rem;
            font-weight: 600;
            color: var(--primary);
            background: white;
            border: none;
            border-radius: 8px;
            cursor: pointer;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        .download-btn:hover {
            transform: translateY(-2px);
            box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
        }

        .toc {
            background-color: #f8faff;
            padding: 1.5rem 2rem;
            border-radius: 12px;
            margin-bottom: 2rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            border: 1px solid #d1d9e6;
        }

        .toc h2 {
            font-size: 1.25rem;
            margin-bottom: 1rem;
            color: var(--primary);
        }

        .toc ul {
            list-style: none;
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(250px, 1fr));
            gap: 0.5rem;
        }

        .toc a {
            color: var(--text);
            text-decoration: none;
            padding: 0.5rem;
            display: block;
            border-radius: 6px;
            transition: background 0.2s;
        }

        .toc a:hover {
            background: var(--bg);
            color: var(--primary);
        }

        .component-section {
            background-color: #f8faff;
            border-radius: 12px;
            padding: 2rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
            page-break-inside: avoid;
            border: 1px solid #d1d9e6;
        }

        .component-section h2 {
            font-size: 1.5rem;
            color: var(--primary);
            margin-bottom: 1.5rem;
            padding-bottom: 0.75rem;
            border-bottom: 2px solid var(--border);
        }

        .section-number {
            display: inline-flex;
            align-items: center;
            justify-content: center;
            width: 2rem;
            height: 2rem;
            background: var(--primary);
            color: white;
            border-radius: 50%;
            font-size: 0.9rem;
            margin-right: 0.5rem;
        }

        .justification, .summary, .full-summary {
            margin-bottom: 1.5rem;
        }

        .justification h3, .summary h3, .full-summary h4 {
            font-size: 1rem;
            color: var(--text-muted);
            margin-bottom: 0.75rem;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }

        .justification p {
            background-color: #eef4ff;
            padding: 1rem;
            border-radius: 8px;
            border-left: 4px solid var(--primary);
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        table tr {
            border-bottom: 1px solid var(--border);
        }

        table tr:last-child {
            border-bottom: none;
        }

        table td {
            padding: 0.75rem;
            text-align: center;
            vertical-align: middle;
        }

        table td.key {
            font-weight: 600;
            width: 30%;
            color: var(--text-muted);
            text-align: center;
        }

        table td.value {
            font-family: 'Monaco', 'Consolas', monospace;
            font-size: 0.9rem;
            text-align: center;
        }

        .full-summary pre {
            background-color: #eef4ff;
            padding: 1rem;
            border-radius: 8px;
            overflow-x: auto;
            font-size: 0.85rem;
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        .llm-explanations {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: linear-gradient(135deg, #f0f7ff 0%, #e8f4f8 100%);
            border-radius: 10px;
            border-left: 4px solid #3b82f6;
        }

        .llm-explanations h4 {
            font-size: 1rem;
            color: #1e40af;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .llm-content {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
            white-space: pre-wrap;
        }

        .component-summary-box {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: linear-gradient(135deg, #f0fdf4 0%, #ecfdf5 100%);
            border-radius: 10px;
            border-left: 4px solid #22c55e;
        }

        .component-summary-box h4 {
            font-size: 1rem;
            color: #166534;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .summary-content {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
            white-space: pre-wrap;
        }

        .summary-content-html {
            font-size: 0.9rem;
            line-height: 1.7;
            color: #334155;
        }

        .dataset-summary-box {
            background: linear-gradient(135deg, #f8fafc 0%, #f1f5f9 100%);
            border-left: 4px solid #6366f1;
        }

        .dataset-summary-box h4 {
            color: #4338ca;
        }

        .metrics-grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
            gap: 1rem;
            margin-bottom: 1.5rem;
        }

        .metric-card {
            background: white;
            border-radius: 8px;
            padding: 1rem;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
            border: 1px solid #e2e8f0;
        }

        .metric-title {
            font-weight: 600;
            color: #4338ca;
            margin-bottom: 0.5rem;
            font-size: 0.9rem;
        }

        .metric-item {
            font-size: 0.85rem;
            color: #475569;
            padding: 0.25rem 0;
        }

        .ai-assessment-container {
            margin-top: 1.5rem;
            padding: 1.25rem;
            background: white;
            border-radius: 10px;
            border: 1px solid #e2e8f0;
        }

        .ai-assessment-container h5 {
            font-size: 1rem;
            color: #1e293b;
            margin-bottom: 1rem;
            font-weight: 600;
        }

        .assessment-tables {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1.5rem;
        }

        .assessment-column {
            padding: 1rem;
            border-radius: 8px;
        }

        .strengths-column {
            background: linear-gradient(135deg, #f0fdf4 0%, #dcfce7 100%);
        }

        .issues-column {
            background: linear-gradient(135deg, #fef2f2 0%, #fee2e2 100%);
        }

        .assessment-column h6 {
            font-size: 0.9rem;
            margin-bottom: 0.75rem;
            font-weight: 600;
        }

        .strengths-column h6 {
            color: #166534;
        }

        .issues-column h6 {
            color: #991b1b;
        }

        .assessment-table {
            width: 100%;
        }

        .assessment-table tr {
            border: none;
        }

        .assessment-table td {
            padding: 0.4rem 0.5rem;
            font-size: 0.85rem;
            text-align: left;
            vertical-align: top;
        }

        .strength-icon, .issue-icon {
            width: 24px;
            font-size: 1rem;
        }

        .priority-action {
            margin-top: 1rem;
            padding: 1rem;
            background: linear-gradient(135deg, #fefce8 0%, #fef9c3 100%);
            border-radius: 8px;
            display: flex;
            align-items: flex-start;
            gap: 0.5rem;
        }

        .priority-icon {
            font-size: 1.2rem;
        }

        .priority-text {
            font-size: 0.9rem;
            color: #854d0e;
        }

        .ai-assessment-text {
            white-space: pre-wrap;
            font-size: 0.9rem;
            color: #334155;
        }

        footer {
            text-align: center;
            padding: 2rem;
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        /* Print styles */
        @media print {
            .no-print {
                display: none !important;
            }

            body {
                background: white;}

            .container {
                max-width: none;padding: 0;
            }

            header {
                background: var(--primary) !important;
                -webkit-print-color-adjust: exact;
                print-color-adjust: exact;
            }

            .component-section {
                box-shadow: none;
                border: 1px solid var(--border);
                break-inside: avoid;
            }

            .download-btn {
                display: none;
            }
        }
        """

    def _get_scripts(self) -> str:
        return """
        // Smooth scrolling for TOC links
        document.querySelectorAll('.toc a').forEach(anchor => {
            anchor.addEventListener('click', function(e) {
                e.preventDefault();
                const target = document.querySelector(this.getAttribute('href'));
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
            });
        });
        """
