NUM_EXAMPLES_LLM = 5

DEFAULT_LLM_MODEL = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
DEFAULT_LLM_MAX_TOKENS = 256
DEFAULT_LLM_TEMPERATURE = 0.3
DEFAULT_LLM_TIMEOUT = 30

POLARS_SIZE_THRESHOLD_MB = 100
LARGE_DATASET_SAMPLE_SIZE = 50000

LOW_DUPLICATES_RATIO = 0.001
MEDIUM_DUPLICATES_RATIO = 0.01

LOW_NEAR_DUPLICATE_RATIO = 0.005
MEDIUM_NEAR_DUPLICATE_RATIO = 0.02

OUTLIER_N_ESTIMATORS = 200
OUTLIER_CONTAMINATION = "auto"
OUTLIER_CARDINALITY_THRESHOLD = 0.85
OUTLIER_MIN_UNIQUE_FOR_ID = 50
OUTLIER_MAX_EXPLAIN_FEATURES = 5

CATEGORICAL_MIN_FREQUENCY_THRESHOLD = 0.01
CATEGORICAL_CARDINALITY_THRESHOLD = 0.8
CATEGORICAL_MIN_NULL_RATIO_WARN = 0.5
CATEGORICAL_MAX_EXPLANATIONS_PER_COL = 5

DISTRIBUTION_EPOCHS = 100
DISTRIBUTION_BATCH_SIZE = 32
DISTRIBUTION_LEARNING_RATE = 1e-3
DISTRIBUTION_HIDDEN_FACTORS = [0.5, 0.25]
DISTRIBUTION_EARLY_STOP_PATIENCE = 10
DISTRIBUTION_VALIDATION_SPLIT = 0.2
DISTRIBUTION_THRESHOLD_PERCENTILE = 95.0
DISTRIBUTION_MIN_ROWS = 10

LABEL_NOISE_CV_FOLDS = 5
LABEL_NOISE_N_PERMUTATIONS = 20
LABEL_NOISE_CONFIDENCE_THRESHOLD = 0.5
LABEL_NOISE_MIN_ROWS = 10

NEAR_DUPLICATE_SIMILARITY_THRESHOLD = 0.8
NEAR_DUPLICATE_NUM_PERM = 128
NEAR_DUPLICATE_NUM_BANDS = 32
NEAR_DUPLICATE_NGRAM_SIZE = 3
NEAR_DUPLICATE_MAX_PAIRS = 100

RELATIONAL_FD_CONFIDENCE_THRESHOLD = 0.95
RELATIONAL_MAX_FD_DETERMINANT_SIZE = 2
RELATIONAL_MAX_VIOLATIONS = 50

COMPOSITE_N_BOOTSTRAP = 30
COMPOSITE_MISSING_RATIO_THRESHOLD = 0.05
COMPOSITE_OUTLIER_RATIO_THRESHOLD = 0.1
COMPOSITE_DUPLICATE_RATIO_THRESHOLD = 0.01
COMPOSITE_CORRELATION_THRESHOLD = 0.95
COMPOSITE_IMBALANCE_THRESHOLD = 10.0
COMPOSITE_BOOTSTRAP_SAMPLE_SIZE = 500
COMPOSITE_MIN_ROWS = 5

IDENTIFIER_UNIQUENESS_THRESHOLD = 0.98
IDENTIFIER_MIN_UNIQUE = 50
LOW_CARDINALITY_THRESHOLD = 20

